package frc.lib.helpers.enums;

public enum AutoTable {
	DEFAULT_CUBE, DRIVE_DEFAULT_CUBE, TOP_CUBE, TOP_CUBE_DOCK, TOP_DOUBLE_CUBE_AUTO_BUILDER, MIDDLE_CUBE, MIDDLE_CUBE_DOCK, BOTTOM_CUBE, BOTTOM_CUBE_DOCK, BOTTOM_DOUBLE_CUBE_AUTO_BUILDER, TESTING, NONE
}
